<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|----------------------------------------------------------------------
| Base Site URL
|----------------------------------------------------------------------
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|   http://example.com/
| WARNING: You MUST set this value!
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
*/
$base_url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$base_url .= "://" . @$_SERVER['HTTP_HOST'];
// Menghapus script name untuk mendapatkan path dasar, dan memastikan tidak ada slash ganda
$base_url .= rtrim(str_replace(basename($_SERVER['SCRIPT_NAME']), "", $_SERVER['SCRIPT_NAME']), '/');
$config['base_url'] = $base_url;


/*
|----------------------------------------------------------------------
| Index File
|----------------------------------------------------------------------
| Typically this will be your index.php file. If you are using mod_rewrite
| to remove the page, set this variable to blank.
*/
$config['index_page'] = '';

/*
|----------------------------------------------------------------------
| URI Protocol
|----------------------------------------------------------------------
| This item determines which server global should be used to retrieve the
| URI string. The default setting of 'REQUEST_URI' works for most servers.
*/
$config['uri_protocol'] = 'REQUEST_URI';

/*
|----------------------------------------------------------------------
| URL Suffix
|----------------------------------------------------------------------
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
*/
$config['url_suffix'] = '';

/*
|----------------------------------------------------------------------
| Default Language
|----------------------------------------------------------------------
| This determines which set of language files should be used.
*/
$config['language'] = 'indonesia';

/*
|----------------------------------------------------------------------
| Default Character Set
|----------------------------------------------------------------------
| This determines which character set is used by default.
*/
$config['charset'] = 'UTF-8';

/*
|----------------------------------------------------------------------
| Enable/Disable System Hooks
|----------------------------------------------------------------------
| If you would like to use the 'hooks' feature, enable it by setting this variable to TRUE.
*/
$config['enable_hooks'] = FALSE;

/*
|----------------------------------------------------------------------
| Class Extension Prefix
|----------------------------------------------------------------------
| This item allows you to set the filename/classname prefix when extending
| native libraries.
*/
$config['subclass_prefix'] = 'MY_';

/*
|----------------------------------------------------------------------
| Composer Auto-loading
|----------------------------------------------------------------------
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script.
*/
$config['composer_autoload'] = FALSE;

/*
|----------------------------------------------------------------------
| Allowed URL Characters
|----------------------------------------------------------------------
| Specify which characters are permitted within your URLs.
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|----------------------------------------------------------------------
| Enable Query Strings
|----------------------------------------------------------------------
| You can optionally enable standard query string based URLs.
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|----------------------------------------------------------------------
| Allow $_GET Array
|----------------------------------------------------------------------
| By default, CodeIgniter enables access to the $_GET array.
*/
$config['allow_get_array'] = TRUE;

/*
|----------------------------------------------------------------------
| Error Logging Threshold
|----------------------------------------------------------------------
| You can enable error logging by setting a threshold over zero.
*/
$config['log_threshold'] = 1;

/*
|----------------------------------------------------------------------
| Error Logging Directory Path
|----------------------------------------------------------------------
| Leave this BLANK unless you would like to set something other than the default application/logs/ directory.
*/
$config['log_path'] = '';

/*
|----------------------------------------------------------------------
| Log File Extension
|----------------------------------------------------------------------
| The default filename extension for log files.
*/
$config['log_file_extension'] = '';

/*
|----------------------------------------------------------------------
| Log File Permissions
|----------------------------------------------------------------------
| The file system permissions to be applied on newly created log files.
*/
$config['log_file_permissions'] = 0644;

/*
|----------------------------------------------------------------------
| Date Format for Logs
|----------------------------------------------------------------------
| Each item that is logged has an associated date. You can use PHP date codes to set your own date formatting.
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|----------------------------------------------------------------------
| Error Views Directory Path
|----------------------------------------------------------------------
| Leave this BLANK unless you would like to set something other than the default application/views/errors/ directory.
*/
$config['error_views_path'] = '';

/*
|----------------------------------------------------------------------
| Cache Directory Path
|----------------------------------------------------------------------
| Leave this BLANK unless you would like to set something other than the default application/cache/ directory.
*/
$config['cache_path'] = '';

/*
|----------------------------------------------------------------------
| Cache Include Query String
|----------------------------------------------------------------------
| Whether to take the URL query string into consideration when generating output cache files.
*/
$config['cache_query_string'] = FALSE;

/*
|----------------------------------------------------------------------
| Encryption Key
|----------------------------------------------------------------------
| If you use the Encryption class, you must set an encryption key.
*/
$config['encryption_key'] = 'ESPdXrhqF2UG#6!&SV&7SDYt$qff8Df2';

/*
|----------------------------------------------------------------------
| Session Variables
|----------------------------------------------------------------------
| Configure session settings.
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL; // Set to a writable path if using 'files' driver
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|----------------------------------------------------------------------
| Cookie Related Variables
|----------------------------------------------------------------------
| Configure cookie settings.
*/
$config['cookie_prefix'] = '';
$config['cookie_domain'] = '';
$config['cookie_path'] = '/';
$config['cookie_secure'] = FALSE;
$config['cookie_httponly'] = FALSE;

/*
|----------------------------------------------------------------------
| Global XSS Filtering
|----------------------------------------------------------------------
| Determines whether the XSS filter is always active when GET, POST or COOKIE data is encountered.
*/
$config['global_xss_filtering'] = FALSE;

/*
|----------------------------------------------------------------------
| Cross Site Request Forgery
|----------------------------------------------------------------------
| Enables a CSRF cookie token to be set.
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = [];

/*
|----------------------------------------------------------------------
| Output Compression
|----------------------------------------------------------------------
| Enables Gzip output compression for faster page loads.
*/
$config['compress_output'] = FALSE;

/*
|----------------------------------------------------------------------
| Master Time Reference
|----------------------------------------------------------------------
| Options are 'local' or any PHP supported timezone.
*/
$config['time_reference'] = 'local';

/*
|----------------------------------------------------------------------
| Rewrite PHP Short Tags
|----------------------------------------------------------------------
| If your PHP installation does not have short tag support enabled CI can rewrite the tags on-the-fly.
*/
$config['rewrite_short_tags'] = FALSE;

/*
|----------------------------------------------------------------------
| Reverse Proxy IPs
|----------------------------------------------------------------------
| Whitelist the proxy IP addresses for CodeIgniter to trust.
*/
$config['proxy_ips'] = '';

$config['biaya_admin'] = 2500;
date_default_timezone_set('Asia/Jakarta');
